// frontend/src/components/Sidebar.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Search, Plus } from 'lucide-vue-next'
import { useI18n } from 'vue-i18n'
import ConnectionTree from './ConnectionTree.vue'
import type { Connection } from '../types'

const { t } = useI18n()

const props = defineProps<{
  width: number
  connections: Connection[]
}>()

const emit = defineEmits<{
  (e: 'update:width', width: number): void
  (e: 'new-connection'): void
  (e: 'table-selected', connectionId: string, database: string, tableName: string): void
  (e: 'table-query', connectionId: string, database: string, tableName: string): void
  (e: 'edit-connection', connection: Connection): void
  (e: 'refresh-connection', connectionId: string): void
  (e: 'delete-connection', connectionId: string): void
  (e: 'new-table', connectionId: string, database: string): void
  (e: 'table-import', connectionId: string, database: string, tableName: string): void
  (e: 'table-export', connectionId: string, database: string, tableName: string): void
}>()

const searchQuery = ref('')
const isResizing = ref(false)

const startResize = (e: MouseEvent) => {
  isResizing.value = true
  const startX = e.clientX
  const startWidth = props.width

  const handleMouseMove = (e: MouseEvent) => {
    const newWidth = Math.max(240, Math.min(400, startWidth + (e.clientX - startX)))
    emit('update:width', newWidth)
  }

  const handleMouseUp = () => {
    isResizing.value = false
    document.removeEventListener('mousemove', handleMouseMove)
    document.removeEventListener('mouseup', handleMouseUp)
  }

  document.addEventListener('mousemove', handleMouseMove)
  document.addEventListener('mouseup', handleMouseUp)
}
</script>

<template>
  <aside
    :style="{ width: width + 'px' }"
    class="flex flex-col bg-[#252526] border-r border-[#333] transition-[width] duration-75 relative"
  >
    <div class="p-3 space-y-3">
      <button
        @click="emit('new-connection')"
        class="w-full bg-[#1677ff] hover:bg-[#4096ff] text-white text-xs py-2 rounded-md font-bold transition-all active:scale-[0.98] flex items-center justify-center gap-2"
      >
        <Plus :size="14" />
        {{ t('sidebar.newConnection') }}
      </button>
      <div class="relative">
        <Search :size="14" class="absolute left-2 top-1/2 -translate-y-1/2 text-gray-400" />
        <input
          v-model="searchQuery"
          type="text"
          :placeholder="t('sidebar.filter')"
          class="w-full bg-[#3c3c3c] text-xs pl-8 pr-3 py-1.5 rounded border border-transparent focus:border-[#1677ff] outline-none transition-all text-gray-200"
        />
      </div>
    </div>

    <div class="flex-1 overflow-y-auto custom-scrollbar px-2">
      <ConnectionTree
        :search-query="searchQuery"
        :connections="connections"
        @table-selected="(connId, db, tableName) => emit('table-selected', connId, db, tableName)"
        @table-query="(connId, db, tableName) => emit('table-query', connId, db, tableName)"
        @edit-connection="(conn) => emit('edit-connection', conn)"
        @refresh-connection="(id) => emit('refresh-connection', id)"
        @delete-connection="(id) => emit('delete-connection', id)"
        @new-table="(connId, database) => emit('new-table', connId, database)"
        @table-import="(connId, db, tableName) => emit('table-import', connId, db, tableName)"
        @table-export="(connId, db, tableName) => emit('table-export', connId, db, tableName)"
      />
    </div>

    <!-- Resize handle -->
    <div
      @mousedown="startResize"
      class="absolute right-0 top-0 bottom-0 w-1 cursor-col-resize hover:bg-[#1677ff]/50 transition-colors"
    ></div>
  </aside>
</template>

// frontend/src/components/Sidebar.tsx
import React from 'react';
import { Connection, Table } from '../types';

interface SidebarProps {
  connections: Connection[];
  selectedConnectionId?: string;
  selectedTable?: string;
  tables: Table[];
  onConnectionSelect: (connectionId: string) => void;
  onTableSelect: (tableName: string) => void;
  onNewConnection: () => void;
  onNewTable: () => void;
  onSettings: () => void;
}

export const Sidebar: React.FC<SidebarProps> = ({
  connections,
  selectedConnectionId,
  selectedTable,
  tables,
  onConnectionSelect,
  onTableSelect,
  onNewConnection,
  onSettings,
}) => {
  const groupedConnections = connections.reduce((acc, conn) => {
    const group = conn.group || 'Other';
    if (!acc[group]) {
      acc[group] = [];
    }
    acc[group].push(conn);
    return acc;
  }, {} as Record<string, Connection[]>);

  return (
    <aside className="glass-sidebar w-72 flex flex-col z-20">
      <div className="p-6 flex items-center gap-3">
        <div className="w-10 h-10 rounded-xl bg-primary flex items-center justify-center text-white shadow-lg shadow-primary/20">
          <span className="material-symbols-outlined">database</span>
        </div>
        <div>
          <h1 className="font-bold text-lg leading-tight tracking-tight">DB Studio</h1>
          <p className="text-[10px] text-[#616289] font-semibold dark:text-gray-400 uppercase tracking-widest">Enterprise</p>
        </div>
      </div>

      <div className="px-6 py-4">
        <div className="neumorphic-inset bg-background-light dark:bg-background-dark rounded-xl flex items-center px-4 h-11">
          <span className="material-symbols-outlined text-gray-400 text-[20px]">search</span>
          <input
            className="bg-transparent border-none focus:ring-0 text-sm w-full placeholder:text-gray-400"
            placeholder="Search databases..."
            type="text"
          />
        </div>
      </div>

      <nav className="flex-1 overflow-y-auto px-4 custom-scrollbar">
        <div className="space-y-6 pt-6">
          {Object.entries(groupedConnections).map(([group, conns]) => (
            <div key={group}>
              <div className="flex items-center justify-between px-2 mb-2">
                <span className="text-[11px] font-bold uppercase tracking-wider text-[#616289]">{group}</span>
                <span className="material-symbols-outlined text-[16px] cursor-pointer text-[#616289] hover:text-primary transition-colors">expand_more</span>
              </div>
              <div className="space-y-1">
                {conns.map((conn) => (
                  <div key={conn.id}>
                    <div
                      className={`flex items-center gap-3 px-3 py-2.5 rounded-xl cursor-pointer group transition-all ${
                        selectedConnectionId === conn.id
                          ? 'bg-primary/10 text-primary border border-primary/20'
                          : 'hover:bg-black/5 dark:hover:bg-white/5'
                      }`}
                      onClick={() => onConnectionSelect(conn.id)}
                    >
                      <span className="material-symbols-outlined text-[20px]">
                        {conn.type === 'postgresql' ? 'storage' : conn.type === 'mysql' ? 'table_chart' : 'database'}
                      </span>
                      <span className="text-sm font-semibold flex-1">{conn.name}</span>
                      <div className={`w-2 h-2 rounded-full ${
                        conn.status === 'connected' 
                          ? 'bg-emerald-status shadow-[0_0_8px_#10B981]' 
                          : 'bg-gray-400 opacity-50'
                      }`}></div>
                    </div>
                    {selectedConnectionId === conn.id && tables.length > 0 && (
                      <div className="mt-2 ml-4 border-l border-gray-200 dark:border-gray-800 space-y-1">
                        {tables.map((table) => (
                          <div
                            key={table.name}
                            className={`flex items-center gap-2 px-3 py-2 ml-3 rounded-lg cursor-pointer text-sm group transition-all ${
                              selectedTable === table.name
                                ? 'bg-primary/5 text-primary border border-primary/10'
                                : 'hover:bg-black/5 dark:hover:bg-white/5'
                            }`}
                            onClick={() => onTableSelect(table.name)}
                          >
                            <span className="material-symbols-outlined text-[18px] text-gray-400 group-hover:text-primary">
                              {table.type === 'view' ? 'view_list' : 'table_chart'}
                            </span>
                            <span className={selectedTable === table.name ? 'font-medium' : 'text-gray-700 dark:text-gray-300'}>
                              {table.name}
                            </span>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </nav>

      <div className="p-6 border-t border-[#E2E8F0] dark:border-gray-800">
        <button
          className="w-full flex items-center justify-center gap-2 p-3 rounded-xl neumorphic-card text-xs font-bold text-[#616289] hover:text-primary transition-all"
          onClick={onSettings}
        >
          <span className="material-symbols-outlined text-[18px]">settings</span>
          Settings
        </button>
      </div>
    </aside>
  );
};
